disabled_rules:
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - function_parameter_count
  - identifier_name
  - large_tuple
  - line_length
  - trailing_whitespace
  - type_body_length
  - unused_optional_binding
  - vertical_whitespace
excluded:
  - build
